### ISSUE TITLE
Add NYT Strands

### ISSUE THREAD

**Issue by JorgenLohne** [PeterKrooni/dailydle-bot#16]
Legge til det nye New York Times spillet :)

**Comment by PeterKrooni** [comment]
step one blir vel å forstå wtf scoren e for noe

**Comment by JorgenLohne** [comment]
> step one blir vel å forstå wtf scoren e for noe

Ekesmpel resultat fra i dag:

![image](https://github.com/PeterKrooni/dailydle-bot/assets/36697655/240dbebc-235f-44a1-8628-df2e33f4ed5b)


> Strands #4
> “Don’t do it!”
> 💡🔵💡🔵
> 💡🔵🔵🔵
> 🔵🟡🔵


Går vell kun an å dele hvis en fullførrer?
💡 = hint. Om å bruke minst hint kanskje? 
Sorterer først etter antall hint, færre er bedre, sortere etter date-time for tie-breakers, føsrt ferdig e bedre.

**Comment by JorgenLohne** [comment]
Ser nå at antall blå prikker før gul prikk er antall ord som du gjettet før spanagrammet.

E.g.

Strands #5
“Do the do”
🔵🔵🟡🔵
🔵🔵🔵

"Jørgen found the spanagram after two words, using no hints" elrns.
